export const ASSET_KEYS = {
  images: {
    background1: 'background1',
    background2: 'background2',
    background3: 'background3',
    beam: 'beam',
    player: 'player',
    mob1: 'mob1',
    mob2: 'mob2',
    mob3: 'mob3',
    mob4: 'mob4',
    lion: 'lion',
    bullet: 'bullet',
    explosion: 'explosion',
    clawWhite: 'clawWhite',
    clawYellow: 'clawYellow',
    catnip: 'catnip',
    expUp: 'expUp',
  },
  audios: {
    beam: 'beam_audio',
    scratch: 'scratch_audio',
    hitMob: 'hitMob_audio',
    growl: 'growl_audio',
    explosion: 'explosion_audio',
    expUp: 'expUp_audio',
    hurt: 'hurt_audio',
    nextLevel: 'nextLevel_audio',
    gameOver: 'gameOver_audio',
    gameClear: 'gameClear_audio',
    pauseIn: 'pauseIn_audio',
    pauseOut: 'pauseOut_audio',
  },
  fonts: {
    pixelFont: 'pixelFont',
  },
  anims: {
    mob1: 'mob1_anim',
    mob2: 'mob2_anim',
    mob3: 'mob3_anim',
    mob4: 'mob4_anim',
    lion: 'lion_anim',
    lionIdle: 'lionIdle_anim',
    player: 'player_anim',
    playerIdle: 'playerIdle_anim',
    explode: 'explode_anim',
    scratchWhite: 'scratchWhite_anim',
    scratchYellow: 'scratchYellow_anim',
    catnip: 'catnip_anim',
    expRed: 'expRed_anim',
    expBlue: 'expBlue_anim',
    expYellow: 'expYellow_anim',
    expGreen: 'expGreen_anim',
  },
} as const;
